### ISSUE TITLE
Decouple rumors-ai-bert from rumors-ai

### ISSUE THREAD

**Issue by godgunman** [cofacts/rumors-ai-bert#5]
To see https://github.com/cofacts/rumors-ai-bert/tree/master/GPU_host

https://github.com/cofacts/rumors-ai-bert/blob/50705367faf152e6628fce705ab93a52e3a304ef/GPU_host/predict_ModelA.sh#L5

**Comment by gary9630** [comment]
Done. Currently, all scripts/programs/data are used in this repo.
